# -*- coding:utf-8 -*-

bootstrap_servers=["10.20.30.48"]
COUNT_NUM = 2100
YY_HOST = "10.20.30.81"
YY_PORT = 6379
YW_HOST = "10.20.50.11"
YW_PORT = 6379
HBASE_LOG_ADDERSS = "10.20.50.31"
HBASE_LOG_PORT = 9090
HBASE_ADDERSS = "10.10.30.30"
HBASE_PORT = 9090
REDIS_HOST = "10.10.21.18"
REDIS_PORT = 6379
HBASE_TEST_ADDERSS = "10.20.30.47"
REDIS_TEST_HOST = "10.10.20.92"
REDIS_TEST_PORT = 6382
ELASTIC_TIMEOUT = 60
ES_ADDR = ["http://data_sync:sync0715@10.20.20.38:9200",
            "http://data_sync:sync0715@10.20.20.38:9201",
            "http://data_sync:sync0715@10.20.20.38:9202",
            "http://data_sync:sync0715@10.20.20.38:9203",
            "http://data_sync:sync0715@10.20.20.37:9200",
            "http://data_sync:sync0715@10.20.20.35:9200",
            "http://data_sync:sync0715@10.20.20.36:9200",
            "http://data_sync:sync0715@10.20.30.103:9200",
            "http://data_sync:sync0715@10.20.20.34:9200"]
ES_TEST_ADDR = ["http://elastic:asd123@10.10.20.41:9200",
            "http://elastic:asd123@10.10.20.42:9200",
            "http://elastic:asd123@10.10.20.43:9200"]
ES_SF_ADDR = ["http://elastic:asd123@10.20.30.42:9200",
                "http://elastic:asd123@10.20.30.43:9200",
                "http://elastic:asd123@10.20.30.44:9200",
                "http://elastic:asd123@10.20.30.45:9200",
                "http://elastic:asd123@10.20.30.46:9200"]
ES_WX_ADDR = ["http://elastic:asd123@10.20.20.38:9200",
                "http://elastic:asd123@10.20.20.37:9200",
                "http://elastic:asd123@10.20.20.36:9200",
                "http://elastic:asd123@10.20.20.35:9200",
                "http://elastic:asd123@10.20.20.34:9200"]
ES_LOG_ADDR = ["http://elastic:asd123@10.20.50.32:9200",
                "http://elastic:asd123@10.20.50.33:9200",]
HARM_INFO_ZIDUAN = {
    "INFO_TABLE":"xw_info",
    "WEIBO_INFO_TABLE":"wb_info",
    "WECHAT_INFO_TABLE":"wx_info",
    "WEIBO_TRANSFER_TABLE":"wb_transfer",
    "MONITOR_INFO_TABLE":"forum_info",
    "TIEBA_FLOOR_TABLE":"tb_floor",
    "WEIBO_USER_TABLE":"wb_user",
    "DOUYIN_INFO_TABLE":"dy_info",
    "DOUYIN_COMMENT_TABLE":"dy_comment"
}
#同步队列
redis_insert_ziduan = {
    "xw_info_test":"es:news:insert:info_test",
    "tb_floor":"es:tb:insert:floor",
    "tb_visit":"es:tb:insert:visit",
    "tb_origin":"es:tb:insert:origin",
    "tb_peo":"es:tb:insert:peo",
    "tb_con":"es:tb:insert:con",
    "tb_tz":"es:tb:insert:tz",
    "wx_info":"es:wechat:insert:info",
    "wx_bak_info":"es:bak:wechat:info",
    "wechat":"es:wangxin:wechat:info",
    "weibo":"es:wangxin:weibo:info",
    "forum":"es:wangxin:forum:info",
    "news":"es:wangxin:news:info",
    "wx_user":"es:wechat:insert:user",
    "wx_group":"es:wechat:insert:group",
    "wx_comment":"es:wechat:insert:comment",
    "xw_info":"es:news:insert:info",
    "xw_origin":"es:news:insert:origin",
    "xw_bak_info":"es:bak:insert:news",
    "xw_user":"es:news:insert:user",
    "xw_comment":"es:news:insert:comment",
    "xw_del_info":"es:news:del:info",
    "wb_comment":"es:weibo:insert:comment",
    "wb_fans":"es:weibo:insert:fans",
    "wb_user":"es:weibo:insert:user",
    "wb_like":"es:weibo:insert:like",
    "wb_follow":"es:weibo:insert:follower",
    "wb_transfer":"es:weibo:insert:transfer",
    "wb_info":"es:weibo:insert:info",
    "wb_bak_info":"es:bak:insert:weibo",
    "forum_info":"es:forum:insert:info",
    "forum_bak_info":"es:bak:insert:forum",
    "image":"es:image:insert:info",
    "audio":"es:audio:insert:info",
    "audioaas":"es:audioaasmap:insert:info",
    "video":"es:video:insert:info",
    "site_record":"es:spark:site:record",
    "dy_info":"es:dy:insert:info",
    "dy_user":"es:dy:insert:user",
    "dy_comment":"es:dy:insert:comment",
    "statistics_info":"es:statistics:insert:info",
}
#微信(专题)
WX_INFO_PARAM ={
    "wx_article_url":"url",
    "wx_nick_name":"nick_name",
    "wx_wechat_key":"user_id",
    "wx_group_url":"group_url","wx_user_logo":"logo","wx_like_num":"like_num","wx_read_num":"read_num",
    "wx_user_name":"user_name","wx_title":"title","wx_content":"content","wx_cover":"cover","wx_images":"images",
    "wx_scraptime":"spider_time","wx_pubtime":"publish_time","wx_updatetime":"updatetime","wx_thematic_ids":"thematic_ids",
    "wx_topic_id":"topic_id","wx_hot_word_id":"hot_word_id","wx_harmful_type_confirm":"harmful_type_confirm",
    "wx_harmful_confirm_time":"harmful_confirm_time","wx_harmful_confirm":"harmful_confirm","wx_content_has_xj_placename":"content_has_xj_placename",
    "wx_content_xj_placename":"content_xj_placename","wx_analysis_method":"analysis_method","wx_snapshot_url":"snapshot_url",
    "wx_tendentiousness":"tendentiousness","wx_title_lang":"title_lang","wx_content_lang":"content_lang","wx_harmful_type_model_tag":"harmful_type_model_tag",
    "wx_harmful_type_model_time":"harmful_type_model_time","wx_harmful_type_keyword":"harmful_type_keyword",
    "wx_harmful_type_keyword_time":"harmful_type_keyword_time",
    "wx_harmful_type_image_tag":"harmful_type_image_tag",
    "wx_harmful_type_image_url":"harmful_type_image_url",
    "wx_harmful_type_image_time":"harmful_type_image_time",
    "wx_harmful_type_audio_tag":"harmful_type_audio_tag","wx_harmful_type_audio_url":"harmful_type_audio_url",
    "wx_harmful_type_audio_time":"harmful_type_audio_time","wx_harmful_type_video_tag":"harmful_type_video_tag",
    "harmful_type_video_url":"harmful_type_video_url","harmful_type_video_time":"harmful_type_video_time","wx_vip_ids":"vip_ids",
    "wx_harmful_type":"harmful_type","wx_heat_number":"heat_number","wx_harmful_type_latest_time":"harmful_type_latest_time",
    "wx_harmful_keyword_json":"harmful_keyword_json","wx_thematic_kw":"thematic_kw","wx_thematic_image":"thematic_image",
    "wx_thematic_audio":"thematic_audio","wx_thematic_video":"thematic_video","wx_thematic_text":"thematic_text",
    "wx_content_keywords":"content_keyword","wx_pn_country":"pn_country","wx_pn_province":"pn_province",
    "wx_pn_municipality":"pn_municipality","wx_pn_district":"pn_district","wx_pn_literal":"literal",
    "wx_pn_related":"related","wx_desc":"desc","wx_status":"status",
    "wx_websiteId":"websiteId",
    "wx_recordPlace":"recordPlace",
    "wx_recordNo":"recordNo",
    "wx_websiteName":"websiteName",
    "wx_contentUrl":"contentUrl",
    "wx_websiteTitle":"websiteTitle",
    "wx_mainWebsiteUrl":"mainWebsiteUrl",
    "wx_source":"source",
    "wx_content_md5":"content_md5",
    "wx_content_md5_status":"content_md5_status",
    "wx_recordCode":"recordCode",
    "wx_harmful_type_image_tag_search":"harmful_type_image_tag_search",
    "wx_harmful_type_image_url_search":"harmful_type_image_url_search",
    "wx_image_harmful_type":"image_harmful_type",
    "wx_image_harmful_tag":"image_harmful_tag",
    "wx_image_harmful_url":"image_harmful_url",
    "wx_image_harmful_time":"image_harmful_time",
    "wx_title_md5":"title_md5",
    "wx_harmful_type_confirm_dz":"harmful_type_confirm_dz",
    "wx_harmful_confirm_time_dz":"harmful_confirm_time_dzv",
    "wx_harmful_degree": "harmful_degree",
    "wx_harmful_degree_formula": "harmful_degree_formula",
    "wx_web_country":"web_country",
    "wx_web_province": "web_province",
    "wx_web_city": "web_city",
    "wx_web_county": "web_county",
    "wx_web_local": "web_local",
}
#(网信)
WX_WECHAT_PARAM = {
    "wx_article_url":"url","wx_nick_name":"nick_name","wx_user_name":"user_name","wx_title":"title","wx_content":"content",
    "wx_cover":"cover","wx_scraptime":"spider_time","wx_pubtime":"publish_time","wx_content_xj_placename":"content_xj_placename",
    "wx_content_has_xj_placename":"content_has_xj_placename","wx_snapshot_url":"snapshot_url",
    "wx_tendentiousness":"tendentiousness","wx_title_lang":"title_lang","wx_content_lang":"content_lang"
}
WX_WECHAT_COMMENT = {
    "wx_ct_article_url":"url","wx_ct_nick_name":"nick_name","wx_ct_content":"content",
    "wx_ct_pubtime":"publish_time","wx_ct_reply":"reply","wx_ct_like_num":"like_num",
    "wx_ct_updatetime":"spider_time","wx_ct_parent_nick_name":"parent_nick_name",
    "wx_ct_parent_user_name":"parent_user_name"
}
WX_WECHAT_USER = {
    "wx_wechat_id":"user_name","wx_wechat_name":"nick_name",
    "wx_wechat_logo":"logo","wx_wechat_desc":"desc",
    "wx_wechat_body":"body","wx_wechat_scraptime":"spider_time",
    "wx_wechat_harmful_num":"harmful_num"
}
WX_WECHAT_GROUP = {
    "wx_group_wechat_id":"user_name","all_publish_time":"publish_time",
    "all_spider_time":"spider_time","wx_group_relate":"relate",
    "wx_group_lord":"lord","wx_group_vice":"vice",
}
#专题
INFO_TABLE ={
    "web_status":"status",
    "web_info_website_url":"website_url",
    "web_info_title":"title",
    "web_info_comments_num":"comments_num",
    "web_info_author":"author",
    "web_info_editor":"editor",
    "web_info_desc":"desc",
    "web_info_content":"content",
    "web_info_images":"images",
    "web_info_push_time":"publish_time",
    "web_info_spider_time":"spider_time",
    "web_info_domain":"domain",
    "web_info_news_url":"url",
    "web_info_news_from":"news_from",
    "web_info_like_num":"like_num",
    "web_info_update_time":"updatetime",
    "web_info_is_news":"is_news",
    "web_info_web_local":"web_local",
    "web_info_web_inner":"web_inner",
    "web_info_web_type":"web_type",
    "web_info_history_effectiveness":"history_effectiveness",
    "web_thematic_ids":"thematic_ids",
    "web_topic_id":"topic_id",
    "web_hot_word_id":"hot_word_id",
    "web_harmful_type_confirm":"harmful_type_confirm",
    "web_harmful_confirm_time":"harmful_confirm_time",
    "web_harmful_confirm":"harmful_confirm",
    "web_content_has_xj_placename":"content_has_xj_placename",
    "web_content_xj_placename":"content_xj_placename",
    "web_analysis_method":"analysis_method",
    "web_snapshot_url":"snapshot_url",
    "web_tendentiousness":"tendentiousness",
    "web_title_lang":"title_lang",
    "web_content_lang":"content_lang",
    "web_harmful_type_model_tag":"harmful_type_model_tag",
    "web_harmful_type_model_time":"harmful_type_model_time",
    "web_harmful_type_keyword":"harmful_type_keyword",
    "web_harmful_type_keyword_time":"harmful_type_keyword_time",
    "web_harmful_type_image_tag":"harmful_type_image_tag",
    "web_harmful_type_image_url":"harmful_type_image_url",
    "web_harmful_type_image_time":"harmful_type_image_time",
    "web_harmful_type_audio_tag":"harmful_type_audio_tag",
    "web_harmful_type_audio_url":"harmful_type_audio_url",
    "web_harmful_type_audio_time":"harmful_type_audio_time",
    "web_harmful_type_video_tag":"harmful_type_video_tag",
    "web_harmful_type_video_url":"harmful_type_video_url",
    "web_harmful_type_video_time":"harmful_type_video_time",
    "web_vip_ids":"vip_ids",
    "web_harmful_type":"harmful_type",
    "web_heat_number":"heat_number",
    "web_harmful_type_latest_time":"harmful_type_latest_time",
    "web_harmful_keyword_json":"harmful_keyword_json",
    "web_thematic_kw":"thematic_kw",
    "web_thematic_image":"thematic_image",
    "web_thematic_audio":"thematic_audio",
    "web_thematic_video":"thematic_video",
    "web_thematic_text":"thematic_text",
    "web_content_keywords":"content_keyword",
    "web_pn_country":"pn_country",
    "web_pn_province":"pn_province",
    "web_pn_municipality":"pn_municipality",
    "web_pn_district":"pn_district",
    "web_pn_literal":"literal",
    "web_pn_related":"related",
    "web_websiteId":"websiteId",
    "web_recordPlace":"recordPlace",
    "web_recordNo":"recordNo",
    "web_websiteName":"websiteName",
    "web_contentUrl":"contentUrl",
    "web_websiteTitle":"websiteTitle",
    "web_mainWebsiteUrl":"mainWebsiteUrl",
    "web_source":"source",
    "web_info_content_md5":"content_md5",
    "web_info_content_md5_status":"content_md5_status",
    "web_recordCode":"recordCode",
    "web_harmful_type_image_tag_search":"harmful_type_image_tag_search",
    "web_harmful_type_image_url_search":"harmful_type_image_url_search",
    "web_image_harmful_type":"image_harmful_type",
    "web_image_harmful_tag":"image_harmful_tag",
    "web_image_harmful_url":"image_harmful_url",
    "web_image_harmful_time":"image_harmful_time",
    "web_title_md5":"title_md5",
    "web_harmful_type_confirm_dz":"harmful_type_confirm_dz",
    "web_harmful_confirm_time_dz":"harmful_confirm_time_dzv",
	"web_info_website_name":"website_name",
    "web_harmful_degree": "harmful_degree",
    "web_harmful_degree_formula": "harmful_degree_formula",
    "web_info_content_label":"content_label",
    "web_info_keywords_type":"keywords_type",
    "web_info_type_keywords":"type_keywords",
    "web_type_code":"type_code",
    "web_type_rules":"type_rules",
    "web_info_web_is_newswebsite":"web_is_newswebsite",
    "web_info_web_country":"web_country",
    "web_info_web_province": "web_province",
    "web_info_web_city": "web_city",
    "web_info_web_county": "web_county",
}
NEWS ={
    "web_info_website_url":"website_url",
    "web_info_title":"title",
    "web_info_comments_num":"comments_num",
    "web_info_author":"author",
    "web_info_editor":"editor",
    "web_info_content":"content",
    "web_info_news_url":"url",
    "web_info_like_num":"like_num",
    "web_info_push_time":"publish_time",
    "web_info_spider_time":"spider_time",
    "web_info_is_news":"is_news",
    "web_info_web_local":"web_local",
    "web_info_web_inner":"web_inner",
    "web_info_web_type":"web_type",
    "web_content_has_xj_placename":"content_has_xj_placename",
    "web_content_xj_placename":"content_xj_placename",
    "web_snapshot_url":"snapshot_url",
    "web_tendentiousness":"tendentiousness",
    "web_title_lang":"title_lang",
    "web_content_lang":"content_lang"
}
NEWS_PERSON_TABLE = {
    "xw_ps_domain": "domain",
    "xw_ps_nick_name": "nick_name",
    "xw_ps_place": "place",
    "xw_ps_spider_time": "spider_time",
    "xw_ps_person_ID": "person_ID"
}
NEWS_COMMENT_TABLE ={
    "xw_ct_news_url":"news_url",
    "xw_ct_person_rowkey":"person_rowkey",
    "xw_ct_push_time":"publish_time",
    "xw_ct_reply_up_id":"reply_up_id",
    "xw_ct_reply_content":"reply_content",
    "xw_ct_like_num":"like_num",
    "xw_ct_spider_time":"spider_time",
    "xw_ct_cilent":"cilent",
    "xw_ct_down_num":"down_num",
    "xw_ct_reply_id":"reply_id",
    "xw_ct_nick_name":"nick_name"
}
NEWS_ORIGIN_TABLE = {
    "web_local":"web_local",
    "web_inner":"web_inner",
    "web_type":"web_type",
    "domain":"domain",
    "website_name":"website_name",
    "website_url":"website_url",
    "spider_time":"spider_time",
    "harmful_num":"harmful_num",
    "web_is_newswebsite":"web_is_newswebsite",
    "web_country": "web_country",
    "web_province": "web_province",
    "web_city": "web_city",
    "web_county": "web_county",
    "web_attribute": "web_attribute",
    "web_language": "web_language",
    "web_status": "web_status",
}
WB_COMMENT_PARAM ={
    "wb_ct_user_id":"user_name",
    "wb_ct_user_url":"user_url",
    "wb_ct_nickname":"nick_name",
    "wb_ct_comment_id":"comment_id",
    "wb_ct_content":"content",
    "wb_ct_images":"images",
    "wb_ct_pubtime":"publish_time",
    "wb_ct_like_num":"like_num",
    "wb_ct_spidertime":"spider_time",
    "wb_ct_parent_user_id":"parent_user_name",
    'wb_ct_parent_mid':"parent_mid",
    "wb_ct_parent_user_url":"parent_user_url",
    "wb_ct_parent_nickname":"parent_nick_name",
    "wb_ct_parent_weibo_rowkey":"parent_rowkey",
    "wb_ts_updatetime":"update_time",
    "wb_ct_user_logo":"logo",
    "wb_ct_superior_id":"parent_comment_id",
    "wb_ct_refer_user_name":"refer_user_name",
    "wb_ct_refer_nick_name":"refer_nick_name",
}
WEIBO_FANS_TABLE ={
    "wb_fs_parent_user_id":"parent_user_id",
    "wb_fs_user_id":"user_name",
    "wb_fs_user_url":"user_url",
    "wb_fs_nickname":"nick_name",
    "wb_fs_image":"logo",
    "wb_fs_spidertime":"spider_time",
    "wb_fs_updatetime":"update_time",
}
WEIBO_FOLLOWER_TABLE ={
    "wb_fr_parent_user_id":"parent_user_id",
    "wb_fr_user_id":"user_name",
    "wb_fr_user_url":"user_url",
    "wb_fr_nickname":"nick_name",
    "wb_fr_image":"logo",
    "wb_fr_updatetime":"update_time",
    "wb_fr_spidertime":"spider_time",
}
WEIBO_LIKE_TABLE ={
    "wb_le_user_id":"user_name",
    "wb_le_user_url":"user_url",
    "wb_le_nickname":"nick_name",
    "wb_le_parent_mid":"parent_mid",
    "wb_le_image":"logo",
    "wb_ct_spidertime":"spider_time",
    "wb_le_parent_rowkey":"parent_rowkey",
    "wb_le_updatetime":"update_time",
    "wb_le_parent_nickname":"parent_nick_name",
    "wb_le_parent_user_url":"parent_user_url",
    "wb_le_parent_user_id":"parent_user_name",
}
WEIBO_TRANSFER_TABLE ={
    "wb_ts_transfer_level":"transfer_level",
    "wb_ts_user_id":"user_name",
    "wb_ts_parent_nickname":"parent_nickname",
    "wb_ts_user_url":"user_url",
    "wb_ts_nickname":"nick_name",
    "wb_ts_parent_mid":"parent_mid",
    "wb_ts_pubtime":"publish_time",
    "wb_ts_mid":"mid",
    "wb_ts_spidertime":"spider_time",
    "wb_ts_content_id":"content_id",
    "wb_ts_user_logo":"logo",
    "wb_ts_harmful_type_confirm_dz":"harmful_type_confirm_dz",
    "wb_ts_harmful_confirm_time_dz":"harmful_confirm_time_dzv",
    "wb_ts_weibo_rowkey":"weibo_rowkey",
    "wb_ts_parent_rowkey":"parent_rowkey",
    "wb_ts_parent_user_id":"parent_user_name",
    "wb_ts_parent_user_url":"parent_user_url",
    "wb_ts_parent_user_nickname":"parent_nick_name",
    "wb_ts_updatetime":"update_time",
    "wb_ts_origin_rowkey":"origin_rowkey",
    "wb_ts_origin_mid":"origin_mid"
}
WEIBO_USER_TABLE ={
    "wb_ur_user_id":"user_name",
    "wb_ur_user_url":"user_url",
    "wb_ur_nickname":"nick_name",
    "wb_ur_image":"logo",
    "wb_ur_real_name":"real_name",
    "wb_ur_local":"local",
    "wb_ur_gender":"gender",
    "wb_ur_sexual":"sexual",
    "wb_ur_marriage":"marriage",
    "wb_ur_birthday":"birthday",
    "wb_ur_blood_type":"blood_type",
    "wb_ur_joindate":"joindate",
    "wb_ur_introduction":"introduction",
    "wb_ur_follower":"follower",
    "wb_ur_fans":"fans",
    "wb_ur_weibo":"weibo",
    "wb_ur_updatetime":"update_time",
    "wb_ur_harmful_num":"harmful_num",
    "wb_ur_spidertime":"spider_time",
    "wb_ur_history_nickname":"history_name"
}
#（专题）
WEIBO_INFO_TABLE ={
    "wb_status":"status",
    "wb_user_id":"user_name",
    "wb_user_url":"user_url",
    "wb_nickname":"nick_name",
    "wb_is_trans":"is_trans",
    "wb_origin_id":"origin_id",
    "wb_weibo_id":"weibo_id",
    "wb_weibo_url":"url",
    "wb_content":"content",
    "wb_images":"images",
    "wb_pubtime":"publish_time",
    "wb_mid":"mid",
    "wb_scraptime":"spider_time",
    "wb_transfer_num":"transfer_num",
    "wb_comment_num":"comment_num",
    "wb_like_num":"like_num",
    "wb_updatetime":"updatetime",
    "wb_thematic_ids":"thematic_ids",
    "wb_content_id":"content_id",
    "wb_topic_id":"topic_id",
    "wb_hot_word_id":"hot_word_id",
    "wb_harmful_type_confirm":"harmful_type_confirm",
    "wb_harmful_confirm_time":"harmful_confirm_time",
    "wb_harmful_confirm":"harmful_confirm",
    "wb_has_content_xj_placename":"has_content_xj_placename",
    "wb_content_xj_placename":"content_xj_placename",
    "wb_analysis_method":"analysis_method",
    "wb_snapshot_url":"snapshot_url",
    "wb_tendentiousness":"tendentiousness",
    "wb_title_lang":"title_lang",
    "wb_content_lang":"content_lang",
    "wb_harmful_type_model_tag":"harmful_type_model_tag",
    "wb_harmful_type_model_time":"harmful_type_model_time",
    "wb_harmful_type_keyword":"harmful_type_keyword",
    "wb_harmful_type_keyword_time":"harmful_type_keyword_time",
    "wb_harmful_type_image_tag":"harmful_type_image_tag",
    "wb_harmful_type_image_url":"harmful_type_image_url",
    "wb_harmful_type_image_time":"harmful_type_image_time",
    "wb_harmful_type_audio_tag":"harmful_type_audio_tag",
    "wb_harmful_type_audio_url":"harmful_type_audio_url",
    "wb_harmful_type_audio_time":"harmful_type_audio_time",
    "wb_harmful_type_video_tag":"harmful_type_video_tag",
    "wb_harmful_type_video_url":"harmful_type_video_url",
    "wb_harmful_type_video_time":"harmful_type_video_time",
    "wb_vip_ids":"vip_ids",
    "wb_harmful_type":"harmful_type",
    "wb_heat_number":"heat_number",
    "wb_harmful_type_latest_time":"harmful_type_latest_time",
    "wb_harmful_keyword_json":"harmful_keyword_json",
    "wb_thematic_kw":"thematic_kw",
    "wb_thematic_image":"thematic_image",
    "wb_thematic_audio":"thematic_audio",
    "wb_thematic_video":"thematic_video",
    "wb_thematic_text":"thematic_text",
    "wb_content_keywords":"content_keyword",
    "wb_pn_country":"pn_country",
    "wb_pn_province":"pn_province",
    "wb_pn_municipality":"pn_municipality",
    "wb_pn_district":"pn_district",
    "wb_pn_literal":"literal",
    "wb_pn_related":"related",
    "wb_websiteId":"websiteId",
    "wb_recordPlace":"recordPlace",
    "wb_recordNo":"recordNo",
    "wb_websiteName":"websiteName",
    "wb_contentUrl":"contentUrl",
    "wb_websiteTitle":"websiteTitle",
    "wb_mainWebsiteUrl":"mainWebsiteUrl",
    "wb_source":"source",
    "wb_content_md5":"content_md5",
    "wb_content_md5_status":"content_md5_status",
    "wb_recordCode":"recordCode",
    "wb_harmful_type_image_tag_search":"harmful_type_image_tag_search",
    "wb_harmful_type_image_url_search":"harmful_type_image_url_search",
    "wb_image_harmful_type":"image_harmful_type",
    "wb_image_harmful_tag":"image_harmful_tag",
    "wb_image_harmful_url":"image_harmful_url",
    "wb_image_harmful_time":"image_harmful_time",
    "wb_content_has_xj_placename":"content_has_xj_placename",
    "wb_harmful_type_confirm_dz":"harmful_type_confirm_dz",
    "wb_harmful_confirm_time_dz":"harmful_confirm_time_dzv",
    "wb_harmful_degree": "harmful_degree",
    "wb_harmful_degree_formula": "harmful_degree_formula",
    "wb_keywords_type":"keywords_type",
    "wb_type_keywords":"type_keywords",
    "wb_type_code":"type_code",
    "wb_type_rules":"type_rules",
    "wb_origin_rowkey":"origin_rowkey",
    "wb_origin_mid":"origin_mid",
    "wb_user_logo":"logo",
    "wb_is_remove":"is_valid",
    "wb_video":"video_url",
    "wb_video_length":"video_length",
}
#（网信）
WEIBO_TABLE = {
    "wb_user_id": "user_name",
    "wb_user_url": "user_url",
    "wb_nickname": "nick_name",
    "wb_weibo_id": "weibo_id",
    "wb_weibo_url": "url",
    "wb_content": "content",
    "wb_images": "images",
    "wb_pubtime": "publish_time",
    "wb_scraptime": "spider_time",
    "wb_has_content_xj_placename": "has_content_xj_placename",
    "wb_content_xj_placename": "content_xj_placename",
    "wb_snapshot_url": "snapshot_url",
    "wb_tendentiousness": "tendentiousness",
    "wb_title_lang": "title_lang",
    "wb_content_lang": "content_lang",
}
#（专题）
FORUM_INFO_TABLE = {
    "rowkey":"rowkey",
    "jc_info_website_name":"website_name",
    "jc_websiteId":"websiteId",
    "jc_recordPlace":"recordPlace",
    "jc_recordNo":"recordNo",
    "jc_websiteName":"websiteName",
    "jc_contentUrl":"contentUrl",
    "jc_websiteTitle":"websiteTitle",
    "jc_mainWebsiteUrl":"mainWebsiteUrl",
    "jc_source":"source",
    "jc_status":"status",
    "jc_info_title":"title",
    "jc_info_news_from":"news_from",
    "jc_info_author":"author",
    "jc_info_editor":"editor",
    "jc_info_push_time":"publish_time",
    "jc_info_spider_time":"spider_time",
    "jc_info_images":"images",
    "jc_info_news_url":"url",
    "jc_info_domain":"domain",
    "jc_content":"content",
    "jc_analysis_method":"analysis_method",
    "jc_harmful_keyword_json":"harmful_keyword_json",
    "jc_harmful_type_keyword":"harmful_type_keyword",
    "jc_harmful_type_keyword_time":"harmful_type_keyword_time",
    "jc_harmful_type_latest_time":"harmful_type_latest_time",
    "jc_harmful_type":"harmful_type",
    "jc_harmful_type_image_tag":"harmful_type_image_tag",
    "jc_harmful_type_image_time":"harmful_type_image_time",
    "jc_harmful_type_image_url":"harmful_type_image_url",
    "jc_harmful_type_confirm":"harmful_type_confirm",
    "jc_harmful_confirm_time":"harmful_confirm_time",
    "jc_harmful_confirm":"harmful_confirm",
    "jc_thematic_kw":"thematic_kw",
    "jc_thematic_image":"thematic_image",
    "jc_thematic_audio":"thematic_audio",
    "jc_thematic_video":"thematic_video",
    "jc_thematic_text":"thematic_text",
    "jc_tendentiousness":"tendentiousness",
    "jc_content_keywords":"content_keyword",
    "jc_title_lang":"title_lang",
    "jc_content_lang":"content_lang",
    "jc_pn_country":"pn_country",
    "jc_pn_province":"pn_province",
    "jc_pn_municipality":"pn_municipality",
    "jc_pn_district":"pn_district",
    "jc_pn_literal":"literal",
    "jc_pn_related":"related",
    "jc_info_content_md5":"content_md5",
    "jc_info_content_md5_status":"content_md5_status",
    "jc_recordCode":"recordCode",
    "jc_harmful_type_image_tag_search":"harmful_type_image_tag_search",
    "jc_harmful_type_image_url_search":"harmful_type_image_url_search",
    "jc_image_harmful_type":"image_harmful_type",
    "jc_image_harmful_tag":"image_harmful_tag",
    "jc_image_harmful_url":"image_harmful_url",
    "jc_image_harmful_time":"image_harmful_time",
    "jc_content_has_xj_placename":"content_has_xj_placename",
    "jc_harmful_type_confirm_dz":"harmful_type_confirm_dz",
    "jc_harmful_confirm_time_dz":"harmful_confirm_time_dzv",
    "jc_harmful_degree": "harmful_degree",
    "jc_harmful_degree_formula": "harmful_degree_formula",
}
#（网信）
FORUM_TABLE = {
    "jc_info_website_name":"website_name",
    "jc_info_title":"title",
    "jc_info_push_time":"publish_time",
    "jc_info_spider_time":"spider_time",
    "jc_info_news_url":"url",
    "jc_content":"content"
}
#(贴吧)
TB_FLOOR_PARAM = {
    "tieba_fl_domain":"domain",
    "tieba_fl_domain_name":"domain_name",
    "tieba_fl_from_tb":"tb_name",
    "tieba_fl_from_tb_url":"tb_url",
    "tieba_fl_id":"floor_id",
    "tieba_fl_title":"title",
    "tieba_fl_website_url":"tz_url",
    "tieba_fl_website_urlpage":"url",
    "tieba_fl_reply_boo":"reply",
    "tieba_fl_floor_num":"floor_num",
    "tieba_fl_origin_id":"upper_floor_url",
    "tieba_fl_author_nickname":"nick_name",
    "tieba_fl_author":"user_name",
    "tieba_fl_author_url":"user_url",
    "tieba_fl_content":"content",
    # "tieba_fl_images":"images",
    # "tieba_fl_audio":"audios",
    "tieba_fl_head_images":"logo",
    "tieba_fl_spider_time":"spider_time",
    "tieba_fl_publish_time":"publish_time",
    "tieba_fl_top_id":"top_floor_url",
    "all_fl_equip":"tools",
    # "tieba_fl_video":"videos",
    "tieba_thematic_ids":"thematic_ids",
    "tieba_content_id":"content_id",
    "tieba_topic_id":"topic_id",
    "tieba_hot_word_id":"hot_word_id",
    "tieba_harmful_type_confirm":"harmful_type_confirm",
    "tieba_harmful_confirm_time":"harmful_confirm_time",
    "tieba_harmful_confirm":"harmful_confirm",
    # "tieba_local_related":"local_related",
    "tieba_content_xj_placename":"content_xj_placename",
    "tieba_harmful_type ":"harmful_type",
    "tieba_analysis_method":"analysis_method",
    "tieba_harm_keywords":"harm_keywords",
    # "tieba_harm_timestamp":"harm_timestamp",
    "tieba_snapshot_url":"snapshot_url",
    "tieba_tendentiousness":"tendentiousness",
    "tieba_status":"status",
    "tieba_content_md5":"content_md5",
    "tieba_content_md5_status":"content_md5_status",
    "tieba_recordNo":"recordNo",
    "tieba_mainWebsiteUrl":"mainWebsiteUrl",
    "tieba_websiteName":"websiteName",
    "tieba_recordCode":"recordCode",
    # "tb_image_harmful_type":"image_harmful_type",
    # "tb_image_harmful_tag":"image_harmful_tag",
    # "tb_image_harmful_url":"image_harmful_url",
    # "tb_image_harmful_time":"image_harmful_time",
    "tieba_content_has_xj_placename":"content_has_xj_placename",
    "tieba_content_keywords":"content_keyword",
    "tieba_title_md5":"title_md5",
    "tieba_heat_number":"heat_number",
    "tieba_title_lang":"title_lang",
    "tieba_content_lang":"content_lang",
    "tieba_harmful_degree": "harmful_degree",
    "tieba_harmful_degree_formula": "harmful_degree_formula",
}
TB_PEO_PARAM = {
    "tieba_p_domain":"domain",
    "tieba_p_domain_name": "domain_name",
    "tieba_p_usr_name": "user_name",
    "tieba_p_usr_tbage": "age",
    "tieba_p_say_count": "info_num",
    "tieba_p_spider_time": "spider_time",
    "tieba_p_head_image": "logo",
    "tieba_p_usr_nickname": "nick_name",
    "tieba_p_usr_gender": "gender",
    "tieba_p_usr_url": "user_url",
    "tieba_p_follow": "follow",
    "tieba_p_visit": "visit",
    "tieba_p_fans": "fans",
    "tieba_p_harmful_num":"harmful_num",
}
TB_TZ_PARAM = {
    "tieba_tz_domain":"domain",
    "tieba_tz_domain_name": "domain_name",
    "tieba_tz_title": "title",
    "tieba_tz_head_image": "logo",
    "tieba_tz_author": "user_name",
    "tieba_tz_author_nickname": "nick_name",
    "tieba_tz_author_url": "user_url",
    "tieba_tz_website_url": "tz_url",
    "tieba_tz_spider_time": "spider_time",
    "tieba_tz_publish_time": "publish_time",
    "tieba_tz_reply_count": "reply_num",
    "tieba_tz_scan_count": "read_num",
    "tieba_tz_from_tb": "tb_name",
    "tieba_tz_from_tb_url": "tb_url",
}
TB_ORIGIN_PARAM = {
    "tieba_or_domain":"domain",
    "tieba_or_domain_name": "domain_name",
    "tieba_or_head_image": "logo",
    "tieba_or_website_url": "tb_url",
    "tieba_or_tbname": "tb_name",
    "tieba_or_desc": "desc",
    "tieba_or_interest_count": "follow_num",
    "tieba_or_tzcount": "info_num",
    "tieba_or_catalog_url": "group_url",
    "tieba_or_catalog_name": "group_name",
    "tieba_or_obj_count": "obj_num",
    "tieba_or_vip_count": "vip_num",
    "tieba_or_spider_time": "spider_time",
    "tieba_or_build_time": "build_time",
}
TB_CON_PARAM = {
    "tieba_p_domain":"domain",
    "tieba_p_domain_name": "domain_name",
    "tieba_p_usr_tbage": "age",
    "tieba_p_say_count": "info_num",
    "tieba_p_spider_time": "spider_time",
    "tieba_p_head_image": "logo",
    "tieba_p_usr_nickname": "nick_name",
    "tieba_p_usr_gender": "gender",
    "tieba_p_usr_url": "user_url",
    "tieba_p_con_url": "parent_user_url",
}
TB_VISIT_PARAM = {
    "tieba_p_domain":"domain",
    "tieba_p_domain_name": "domain_name",
    "tieba_p_usr_tbage": "age",
    "tieba_p_say_count": "info_num",
    "tieba_p_spider_time": "spider_time",
    "tieba_p_head_image": "logo",
    "tieba_p_usr_nickname": "nick_name",
    "tieba_p_usr_gender": "gender",
    "tieba_p_usr_url": "user_url",
    "tieba_p_con_url": "parent_user_url",
}
#网站
SITE_RECORD = {
    "websiteId":"websiteId",
    "recordPlace":"recordPlace",
    "recordNo":"recordNo",
    "websiteName":"websiteName",
    "contentUrl":"contentUrl",
    "websiteTitle":"websiteTitle",
    "mainWebsiteUrl":"mainWebsiteUrl",
    "source":"websiteSource",
    "recordCode":"recordCode",
    "domain":"domain",
    "recordIP":"recordIP"
}
#抖音
DOUYIN_INFO_TABLE = {
    "dy_vd_group_id":"group_id",
    "dy_vd_nick_name":"nick_name",
    "dy_vd_ur_logo":"logo",
    "dy_vd_user_name":"user_name",
    "dy_vd_pubtime":"publish_time",
    "dy_vd_image":"images",
    "dy_vd_bit":"bit",
    "dy_vd_transfer_num":"transfer_num",
    "dy_vd_like_num":"like_num",
    "dy_vd_comment_num":"comment_num",
    "dy_vd_desc":"content",
    "dy_vd_id":"video_id",
    "dy_vd_url":"url",
    "dy_vd_fdfs":"video_url",
    "dy_vd_spider_time":"spider_time",
    "dy_harmful_type_image_tag":"harmful_type_image_tag",
    "dy_harmful_type_image_url":"harmful_type_image_url",
    "dy_harmful_type_image_time":"harmful_type_image_time",
    "dy_harmful_type_audio_tag":"harmful_type_audio_tag",
    "dy_harmful_type_audio_url":"harmful_type_audio_url",
    "dy_harmful_type_audio_time":"harmful_type_audio_time",
    "dy_harmful_type_video_tag":"harmful_type_video_tag",
    "dy_harmful_type_video_url":"harmful_type_video_url",
    "dy_harmful_type_video_time":"harmful_type_video_time",
    "dy_pn_country":"pn_country",
    "dy_pn_province": "pn_province",
    "dy_pn_municipality": "pn_municipality",
    "dy_pn_district": "pn_district",
    "dy_pn_literal": "literal",
    "dy_content_has_xj_placename": "content_has_xj_placename",
    "dy_content_xj_placename": "content_xj_placename",
    "dy_tendentiousness": "tendentiousness",
    "dy_content_lang": "content_lang",
    "dy_harmful_type_confirm": "harmful_type_confirm",
    "dy_harmful_confirm_time": "harmful_confirm_time",
    "dy_harmful_type_confirm_dz": "harmful_type_confirm_dz",
    "dy_harmful_confirm_time_dz": "harmful_confirm_time_dz",
    "dy_harmful_confirm": "harmful_confirm",
    "dy_thematic_image": "thematic_image",
    "dy_thematic_text": "thematic_text",
    "dy_recordCode": "recordCode",
    "dy_mainWebsiteUrl": "mainWebsiteUrl",
    "dy_websiteName": "websiteName",
    "dy_recordNo": "recordNo",
    "dy_content_md5": "content_md5",
    "dy_content_md5_status": "content_md5_status",
    "dy_content_keywords": "content_keyword",
    "dy_heat_number": "heat_number",
    "dy_hot_word_id": "hot_word_id",
    "dy_status": "status",
    "dy_vd_length":"video_length",
    "dy_vd_is_remove":"is_remove",
    "dy_vd_update_time":"updatetime",
    "dy_harmful_degree":"harmful_degree",
    "dy_harmful_degree_formula":"harmful_degree_formula",
    "dy_vd_is_local":"web_local",
}
DOUYIN_USER_TABLE = {
    "dy_ur_user_url":"user_url",
    "dy_ur_user_name": "user_name",
    "dy_ur_nick_name": "nick_name",
    "dy_ur_user_id": "user_id",
    "dy_ur_birthday": "birthday",
    "dy_ur_introduction": "introduction",
    "dy_ur_local": "local",
    "dy_ur_constellation": "constellation",
    "dy_ur_joindate": "joindate",
    "wb_ur_nickname": "wb_nick_name",
    "wb_ur_user_id": "wb_user_id",
    "wb_ur_user_url": "wb_user_url",
    "dy_ur_phone": "phone",
    "dy_ur_logo": "logo",
    "dy_ur_vdcount": "vdcount",
    "dy_ur_gender": "gender",
    "dy_ur_follow_num": "follow_num",
    "dy_ur_vd_like_num": "vd_like_num",
    "dy_ur_like_num": "like_num",
    "dy_ur_fans": "fans",
    "dy_ur_spider_time": "spider_time",
    "dy_ur_harmful_num":"harmful_num",
    "dy_ur_update_time":"updatetime",
    "dy_ur_is_local":"web_local",
}
DOUYIN_COMMENT_TABLE = {
    "dy_ct_mid":"mid",
    "dy_ct_nick_name":"nick_name",
    "dy_ct_ur_logo":"logo",
    "dy_ct_group_id":"group_id",
    "dy_ct_user_name":"user_name",
    "dy_ct_content":"content",
    "dy_ct_pubtime":"publish_time",
    "dy_ct_parent_mid":"parent_mid",
    "dy_ct_spider_time":"spider_time",
    "dy_harmful_type":"harmful_type",
    "dy_harmful_type_latest_time":"harmful_type_latest_time",
    "dy_harmful_type_model_tag":"harmful_type_model_tag",
    "dy_harmful_type_model_time":"harmful_type_model_time",
    "dy_harmful_type_keyword":"harmful_type_keyword",
    "dy_harmful_type_keyword_time":"harmful_type_keyword_time",
    "dy_tendentiousness":"tendentiousness",
    "dy_content_lang":"content_lang",
    "dy_content_keywords":"content_keyword",
    "dy_content_has_xj_placename":"content_has_xj_placename",
    "dy_content_xj_placename":"content_xj_placename",
    "dy_pn_country":"pn_country",
    "dy_pn_province": "pn_province",
    "dy_pn_municipality": "pn_municipality",
    "dy_pn_district": "pn_district",
    "dy_pn_literal": "literal",
    "dy_harmful_type_confirm":"harmful_type_confirm",
    "dy_harmful_confirm_time":"harmful_confirm_time",
    "dy_harmful_type_confirm_dz":"harmful_type_confirm_dz",
    "dy_harmful_confirm_time_dz":"harmful_confirm_time_dz",
    "dy_harmful_confirm":"harmful_confirm",
    "dy_ct_update_time":"updatetime",
    "dy_ct_vd_id":"video_id",
}
# 统计信息表字段  需要把文档里面的字段一一对应
# 字段控制都在这个里面，所以以后有谁需要对statistics_info加字段的话，就在这个里面加，然后把它放到服务器上，然后重启服务器对应的python服务就可以
COUNT_INFO_TABLE = {
    "count_dimension": "dimension",
    "count_date_year": "date_year",
    "count_date_month": "date_month",
    "count_type": "type",
    "count_is_remove": "is_remove",
    "count_history_01": "history_01",
    "count_history_02": "history_02",
    "count_history_03": "history_03",
    "count_history_04": "history_04",
    "count_history_05": "history_05",
    "count_history_06": "history_06",
    "count_history_07": "history_07",
    "count_history_08": "history_08",
    "count_history_09": "history_09",
    "count_history_10": "history_10",
    "count_history_11": "history_11",
    "count_history_12": "history_12",
    "count_history_13": "history_13",
    "count_history_14": "history_14",
    "count_history_15": "history_15",
    "count_history_16": "history_16",
    "count_history_17": "history_17",
    "count_history_18": "history_18",
    "count_history_19": "history_19",
    "count_history_20": "history_20",
    "count_history_21": "history_21",
    "count_history_22": "history_22",
    "count_history_23": "history_23",
    "count_history_24": "history_24",
    "count_history_25": "history_25",
    "count_history_26": "history_26",
    "count_history_27": "history_27",
    "count_history_28": "history_28",
    "count_history_29": "history_29",
    "count_history_30": "history_30",
    "count_history_31": "history_31",
    "count_real_time_01": "real_time_01",
    "count_real_time_02": "real_time_02",
    "count_real_time_03": "real_time_03",
    "count_real_time_04": "real_time_04",
    "count_real_time_05": "real_time_05",
    "count_real_time_06": "real_time_06",
    "count_real_time_07": "real_time_07",
    "count_real_time_08": "real_time_08",
    "count_real_time_09": "real_time_09",
    "count_real_time_10": "real_time_10",
    "count_real_time_11": "real_time_11",
    "count_real_time_12": "real_time_12",
    "count_real_time_13": "real_time_13",
    "count_real_time_14": "real_time_14",
    "count_real_time_15": "real_time_15",
    "count_real_time_16": "real_time_16",
    "count_real_time_17": "real_time_17",
    "count_real_time_18": "real_time_18",
    "count_real_time_19": "real_time_19",
    "count_real_time_20": "real_time_20",
    "count_real_time_21": "real_time_21",
    "count_real_time_22": "real_time_22",
    "count_real_time_23": "real_time_23",
    "count_real_time_24": "real_time_24",
    "count_real_time_25": "real_time_25",
    "count_real_time_26": "real_time_26",
    "count_real_time_27": "real_time_27",
    "count_real_time_28": "real_time_28",
    "count_real_time_29": "real_time_29",
    "count_real_time_30": "real_time_30",
    "count_real_time_31": "real_time_31",
    "count_all_01": "count_all_01",
    "count_all_02": "count_all_02",
    "count_all_03": "count_all_03",
    "count_all_04": "count_all_04",
    "count_all_05": "count_all_05",
    "count_all_06": "count_all_06",
    "count_all_07": "count_all_07",
    "count_all_08": "count_all_08",
    "count_all_09": "count_all_09",
    "count_all_10": "count_all_10",
    "count_all_11": "count_all_11",
    "count_all_12": "count_all_12",
    "count_all_13": "count_all_13",
    "count_all_14": "count_all_14",
    "count_all_15": "count_all_15",
    "count_all_16": "count_all_16",
    "count_all_17": "count_all_17",
    "count_all_18": "count_all_18",
    "count_all_19": "count_all_19",
    "count_all_20": "count_all_20",
    "count_all_21": "count_all_21",
    "count_all_22": "count_all_22",
    "count_all_23": "count_all_23",
    "count_all_24": "count_all_24",
    "count_all_25": "count_all_25",
    "count_all_26": "count_all_26",
    "count_all_27": "count_all_27",
    "count_all_28": "count_all_28",
    "count_all_29": "count_all_29",
    "count_all_30": "count_all_30",
    "count_all_31": "count_all_31",
    "count_web_type": "web_type",
    "count_web_country": "web_country",
    "count_web_province": "web_province",
    "count_web_city": "web_city",
    "count_web_county": "web_county",
    "count_web_is_newswebsite": "is_newswebsite",
    "count_website_name": "website_name",
}
ziduan = {
    'tb_floor':TB_FLOOR_PARAM,
    'tb_peo':TB_PEO_PARAM,
    'tb_tz':TB_TZ_PARAM,
    'tb_origin':TB_ORIGIN_PARAM,
    'tb_con':TB_CON_PARAM,
    'tb_visit':TB_VISIT_PARAM,
    "wx_info": WX_INFO_PARAM,
    "wx_comment": WX_WECHAT_COMMENT,
    "wx_user": WX_WECHAT_USER,
    "wx_group": WX_WECHAT_GROUP,
    "wechat": WX_WECHAT_PARAM,
    "xw_info":INFO_TABLE,
    "xw_user":NEWS_PERSON_TABLE,
    "xw_comment":NEWS_COMMENT_TABLE,
    "xw_origin":NEWS_ORIGIN_TABLE,
    "news":NEWS,
    "wb_comment":WB_COMMENT_PARAM,
    "wb_user":WEIBO_USER_TABLE,
    "wb_like":WEIBO_LIKE_TABLE,
    "wb_transfer":WEIBO_TRANSFER_TABLE,
    "wb_info":WEIBO_INFO_TABLE,
    "wb_fans":WEIBO_FANS_TABLE,
    "wb_follow":WEIBO_FOLLOWER_TABLE,
    "weibo":WEIBO_TABLE,
    "forum_info":FORUM_INFO_TABLE,
    "forum":FORUM_TABLE,
    "site_record":SITE_RECORD,
    "dy_info":DOUYIN_INFO_TABLE,
    "dy_user":DOUYIN_USER_TABLE,
    "dy_comment":DOUYIN_COMMENT_TABLE,
    "statistics_info":COUNT_INFO_TABLE,  # 前面为es表名，后面为hbase表名（可以在es建表文档里查到）  这个不一定是es表名，只是一个变量，只不过我习惯写成es表名和hbase表名
}
AUDIO_LIST = ["audio_duration","audio_file_size","audio_info_tablename","audio_info_rowkey","audio_spider_time","audio_url","audio_source_fastdfs_url","audio_fastdfs_url","audio_harmful_type_org","audio_harmful_type_org_time","audio_harmful_type_print","audio_harmful_type_print_time","audio_feature_org","audio_org_time","audio_feature_print","audio_print_time","audio_lang","audio_recognition","audio_recognition_time","audio_is_frome_video","audio_source","audio_source_url","audio_video_rowkey","audio_aas_reg_id","audio_publish_time","audio_is_reduplicated"]
IMAGE_LIST = ["pic_info_tablename","pic_info_rowkey","pic_spider_time","pic_is_in_redis","pic_source_fastdfs_url","pic_image_fastdfs_url","pic_height_width","pic_face_time","pic_face_dfs","pic_harmful_type","pic_harmful_time","pic_category","pic_ocr_lang","pic_ocr_content","pic_ocr_time","pic_is_frame","pic_image_source","pic_source_url","pic_source_transcode_url","pic_publish_time"]
AUDIOAAS_LIST = ["audio_rowkey","infotablename","inforowkey","pubtime","spidtime","audio_source_url","audio_fastdfs_url","audio_file_size","audio_duration"]
VIDEO_LIST = ["video_spider_time","video_url","video_fastdfs_url","video_keyframe_time","video_feature_time","video_audio_fastdfs_url","video_audio_time","video_audio_rowkey","video_audio_time","video_fastdfs_url_ts","video_ts_time","video_publish_time","video_info_tablename","video_source","video_info_rowkey","video_source_url","video_frame_rowkey_prefix","video_is_alignment_with_info","video_frame_fastdfs_url_list"]
list_ziduan = {
    "audio":AUDIO_LIST,
    "image":IMAGE_LIST,
    "video":VIDEO_LIST,
    "audioaas":AUDIOAAS_LIST
}